### ISSUE TITLE
How to get all database from cloudant ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant-labs/data-flow-examples#14]
from given code below rather than getting only `animaldb` i want to access all available databases through the loop, how can I do that?
![image](https://user-images.githubusercontent.com/11150958/37869359-0632e46e-2fd8-11e8-9254-4345206fe2a1.png)

**Comment by emlaver** [comment]
@ZaheerUdDeen the `sql-cloudant` library only supports loading one database at a time.  
I see that you've opened an issue with a similar question in Bahir's JIRA issue tracker.  Let's address this question in JIRA since we don't handle support questions here, only bugs/typos/etc for the examples. Thanks.
